[package]
name = "raku"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.29.0", features = ["crossterm"] }
color-eyre = "0.6.5"
dirs-next = "2.0.0"
fundsp = "0.20.0"
rodio = "0.21.1"
